name: chia_utils
description: Utilities for the Chia blockchain.
version: 1.0.8

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  bech32m: ^0.2.2
  bip39: ^1.0.6
  hex: ^0.2.0
  injector: ^2.0.0
  meta: ^1.7.0
  quiver: ^3.0.1+1

dev_dependencies:
  csv: ^5.0.1
  http: ^0.13.4
  lints: ^1.0.0
  test: ^1.19.3
  very_good_analysis: ^2.4.0
